build:
  maxIssues: 0

complexity:
  LongParameterList:
    functionThreshold: 7
  TooManyFunctions:
    active: false

style:
  MaxLineLength:
    maxLineLength: 150
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreExtensionFunctions: true
  WildcardImport:
    active: false

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable
  PackageNaming:
    active: false
