build:
  maxIssues: 0

complexity:
  LongParameterList:
    functionThreshold: 7
  TooManyFunctions:
    active: false

style:
  MaxLineLength:
    maxLineLength: 150
  WildcardImport:
    active: false

naming:
  PackageNaming:
    active: false
